
DROP DATABASE IF EXISTS AdminDiscord;

CREATE DATABASE AdminDiscord;

USE AdminDiscord;

CREATE TABLE USER(
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    deleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE SERVER(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    img VARCHAR(255)
    );

CREATE TABLE ROOM(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    id_server INT NOT NULL,
    FOREIGN KEY (id_server) REFERENCES SERVER(id) ON DELETE CASCADE
);


CREATE TABLE PRIVATE_CHAT (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id_1 INT NOT NULL,
    user_id_2 INT NOT NULL,
    delete_user_1 BOOLEAN DEFAULT FALSE,
    delete_user_2 BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (user_id_1) REFERENCES USER(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id_2) REFERENCES USER(id) ON DELETE CASCADE,
    UNIQUE(user_id_1, user_id_2)
);


CREATE TABLE SERVER_USER(
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    server_id INT NOT NULL,
    admin BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (user_id) REFERENCES USER(id) ON DELETE CASCADE,
    FOREIGN KEY (server_id) REFERENCES SERVER(id) ON DELETE CASCADE,
    UNIQUE(user_id, server_id)
);



