version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: adminbdds
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234567aA*"  
      MYSQL_DATABASE: "AdminDiscord"       
      MYSQL_USER: "user"                
      MYSQL_PASSWORD: "1234567aA*"     
    ports:
      - "3036:3306"
    volumes:
      - ./bdd.sql:/docker-entrypoint-initdb.d/bdd.sql
      - data:/var/lib/mysql

volumes:
  data:
