#version: '3.8'

#services:
#  mysql:
 #   image: mysql:8.0
   # container_name: adminbdd
    #restart: always
    #environment:
      #MYSQL_ROOT_PASSWORD: "1234567aA*"  
      #MYSQL_DATABASE: "AdminDiscord"       
    #ports:
     # - "3336:3306"
    #volumes:
     # - ./bdd_mysql.sql:/docker-entrypoint-initdb.d/bdd.sql
      #- data:/var/lib/mysql

#volumes:
 # data:
version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: adminbdd
    restart: always
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "1234567aA*"
      POSTGRES_DB: "AdminDiscord"
    ports:
      - "5432:5432"
    volumes:
      - ./bdd_postgres.sql:/docker-entrypoint-initdb.d/bdd.sql
      - pgdata:/var/lib/postgresql/data
  pulsar:
    image: apachepulsar/pulsar:latest
    container_name: pulsar
    command: bin/pulsar standalone
    ports:
      - "6650:6650" 
    volumes:
      - pulsar-data:/pulsar/data
      - pulsar-logs:/pulsar/logs
  mongo:
    image: mongo:6.0
    container_name: discordMongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: "discordMongo"
volumes:
  pulsar-data:
  pulsar-logs:
  pgdata:
  mongo_data:
