version: '3.8'

services:
  discordclient:
    build: ./discord-client
    ports:
      - "8081:80"
    depends_on:
      - adminapi

  adminapi:
    build: ./adminapi
    ports:
      - "8080:8080"
    environment:
      JDBC_URL: "jdbc:mysql://mysql:3306/AdminDiscord"
      DB_USER: "root"
      DB_PASSWORD: "1234567aA*"
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: adminbdd
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234567aA*"  
      MYSQL_DATABASE: "AdminDiscord"       
    ports:
      - "3336:3306"
    volumes:
      - ./bdd.sql:/docker-entrypoint-initdb.d/bdd.sql
      - data:/var/lib/mysql

volumes:
  data:
